# Generated by Django 5.1.2 on 2024-11-15 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
